DELIMITER |
CREATE TRIGGER MaxUsers BEFORE INSERT ON Utenti
FOR EACH ROW
BEGIN
DECLARE num INT;
DECLARE specialty CONDITION FOR SQLSTATE '70125';
SELECT COUNT(*) INTO num FROM Utenti;
IF num>=6 THEN
	SIGNAL SQLSTATE '70125' SET MESSAGE_TEXT = 'Numero massimo di utenti raggiunto (5)';
END IF;
END|
DELIMITER ;
