INSERT INTO Facilities (Nome,Livello) VALUES
('Police portuale','0'),
('Fire Department','0'),
('Capitaneria di porto','0'),
('Tug service','0'),
('Pilots','0'),
('Dry dock','1'),
('Bulk terminal','1'),
('Container terminal','2'),
('Passenger terminal','2'),
('Ore terminal','3'),
('Oil terminal','4'),
('Chemical terminal','4'),
('LPG terminal','4'),
('LNG terminal','4'),
('Fire Department CDS','4');
